# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180224_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.TextField(unique=True),
        ),
    ]
