# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 23:21
from __future__ import unicode_literals

from django.db import migrations

def set_companies(apps,schema_editor):
	Company = apps.get_model("project","Company")

	companies = ["ALTISOURCE","CLEARCAP","CORELOGIC","BPO FULFILLMENT"]

	Company.objects.all().delete()
	for company in companies:
		Company(name=company).save()

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170311_0715'),
    ]

    operations = [
    	migrations.RunPython(set_companies)
    ]
