# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170311_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_assignment_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned by', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_assignment_history',
            },
        ),
        migrations.CreateModel(
            name='Order_status_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status changed by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_status_history',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qc_count',
        ),
        migrations.AddField(
            model_name='order',
            name='is_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Status'),
        ),
        migrations.AddField(
            model_name='order_status_history',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Order'),
        ),
        migrations.AddField(
            model_name='order_status_history',
            name='remarks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Status'),
        ),
        migrations.AddField(
            model_name='order_status_history',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Status'),
        ),
        migrations.AddField(
            model_name='order_assignment_history',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Order'),
        ),
    ]
