# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170311_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='code',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
