# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 23:56
from __future__ import unicode_literals

from django.db import migrations

def set_user_types(apps,schema_editor):
	User_type = apps.get_model("project","User_type")
	User_type.objects.all().delete()

	user_types = [
		{
			"code": "client",
			"name": "Client",
		},
		{
			"code": "cda",
			"name": "CDA",
		},
		{
			"code": "admin",
			"name": "Admin",
		},
	]

	for user_type in user_types:
		User_type(
			code = user_type["code"],
			name = user_type["name"],
		).save()

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_user_type_code'),
    ]

    operations = [
    	migrations.RunPython(set_user_types)
    ]
