# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 23:15
from __future__ import unicode_literals

from django.db import migrations


'''
	Status:
		Active
			Hold
			Assigned
		Completed
			QC
			Submitted
			Assigned
		Cancelled			
			Assigned
'''


def set_default_misc_values(apps,schema_editor):
	Status = apps.get_model("project","Status")
	statuses = ["Active","Completed","Cancelled","Hold","Quality Control","Submitted"]
	Status.objects.all().delete()
	for status in statuses:
		Status(name = status).save()



class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_user_user_type'),
    ]

    operations = [
    	migrations.RunPython(set_default_misc_values)
    ]
