# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170311_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='typee',
        ),
        migrations.AddField(
            model_name='credential',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
