# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170311_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_rush',
            field=models.BooleanField(default=False),
        ),
    ]
