# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170312_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 11, 17, 21, 46, 265650, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
