# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20170312_0121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('client', 'reference_no')]),
        ),
    ]
