# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20170312_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
