# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='active', max_length=200),
            preserve_default=False,
        ),
    ]
