# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reference_no',
            new_name='order_number',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('client', 'order_number')]),
        ),
    ]
