# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_remove_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credential',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Credential'),
            preserve_default=False,
        ),
    ]
