# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_order_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_status_history',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
