# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20170312_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.User_type'),
            preserve_default=False,
        ),
    ]
