# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 23:56
from __future__ import unicode_literals

from django.db import migrations
from ..forms.users import *

def create_super_admin(apps,schema_editor):
	admin_data = {
		"email": "admin@gmail.com",
		"fullname": "admin",
		"password": "123",
		"user_type": 3
	}

	form = Users_create_form(admin_data)

	if form.is_valid():
		save = form.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_user_user_type'),
    ]

    operations = [
    	migrations.RunPython(create_super_admin)
    ]


    email = models.EmailField(max_length = 254, null = False, blank = False, unique = True)
    fullname = models.CharField(max_length = 50, null = False, blank = False)
    user_type = models.ForeignKey("User_type")
    is_active = models.BooleanField(default = True)
    created_on = models.DateTimeField(auto_now_add = True)
    edited_on = models.DateTimeField(auto_now = True)
    deleted = models.BooleanField(default = False)
    USERNAME_FIELD = 'email'
    objects = User_Manager()