# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_order_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_remaining',
            field=models.IntegerField(null=True),
        ),
    ]
