# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20170318_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_photo',
            name='photo_thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=b'orders/photos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='order_photo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_photo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=b'orders/photos/'),
        ),
    ]
