# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20170409_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_photo',
            name='is_deleted',
        ),
    ]
