# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_order_photo_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('filelocation', models.FileField(upload_to=b'orders/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Order')),
            ],
            options={
                'db_table': 'order_document',
            },
        ),
    ]
