# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 15:21
from __future__ import unicode_literals

from django.db import migrations

def create_admin_user(apps,schema_editor):
	User = apps.get_model("project","User")
	User_type = apps.get_model("project","User_type")

	user_type_instance = User_type.objects.get(code = "admin")


	User(
		email = "aldeadmin@gmail.com",
		fullname = "Alde Admin Sabido",
		user_type = user_type_instance,
		password = "123"
	).save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_order_document'),
    ]

    operations = [
    	migrations.RunPython(create_admin_user)
    ]



