# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20170502_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
